make ignored_files supports re
TISUnion/PrimeBackup pull request #33
Opened 2024-06-09 19:35 UTC by chinese-wzq

2024-06-10 01:29 UTC, Fallen-Breath commented
该 PR 的修改破坏了存量部署的配置后向兼容性，请调整实现方式

除此之外，该实现未对文件/文件夹的嵌套关系进行处理，可能会造成意料外的非完整数据备份，这也是需要考虑的

2024-06-10 01:30 UTC, Fallen-Breath requested changes
该 PR 的修改破坏了存量部署的配置后向兼容性，请调整实现方式

除此之外，该实现未对文件/文件夹的嵌套关系进行处理，可能会造成意料外的非完整数据备份，这也是需要考虑的

2024-06-10 04:28 UTC, chinese-wzq commented
> 该 PR 的修改破坏了存量部署的配置后向兼容性，请调整实现方式
> 
> 除此之外，该实现未对文件/文件夹的嵌套关系进行处理，可能会造成意料外的非完整数据备份，这也是需要考虑的

第二点可以具体举例说说嘛？

2024-06-10 04:36 UTC, Fallen-Breath commented
> 第二点可以具体举例说说嘛

建议自行阅读相关代码实现

> 什么情况下无法用正则表达式匹配？

该观点我未曾提出过

2024-06-10 04:46 UTC, chinese-wzq commented
第一点可以考虑将原始的ignored_files保留，新增一个配置项ignored_files_json，不过新增的配置项能否自动添加到用户config.json中呢？
第二点我实在没有理解你的意思，麻烦讲得再详细一点

2024-06-10 05:06 UTC, Fallen-Breath commented
自己看一下相关代码是怎么使用这个函数的吧

理解清楚修改的代码的用处功能，是交 PR 前必须的操作呀，不能连相关改动的代码是干什么的都不知道，就随便改下交 PR

2024-07-12 05:11 UTC, chinese-wzq commented
> 自己看一下相关代码是怎么使用这个函数的吧
> 
> 理解清楚修改的代码的用处功能，是交 PR 前必须的操作呀，不能连相关改动的代码是干什么的都不知道，就随便改下交 PR

我现在仔细看了以下__scan_files，好像改动前后没有逻辑上没有什么差别呀，能指出来吗

2024-07-12 05:42 UTC, chinese-wzq commented
你的第一个问题现在解决了

2024-07-12 06:37 UTC, Fallen-Breath commented on prime_backup/config/backup_config.py
> +		'server/session.lock',
错误配置的默认值

2024-07-12 06:41 UTC, chinese-wzq commented on prime_backup/config/backup_config.py
> +		'server/session.lock',
是等效的

2024-07-12 06:42 UTC, Fallen-Breath commented on docs/config.md
> +It is recommended to use `ignored_files_regex` to support more accurate and specific matching methods.
`ignored_files_regex` 不是 `ignored_files` 的完全替代

2024-07-12 06:43 UTC, Fallen-Breath commented on prime_backup/config/backup_config.py
> +			if re.match(item, str(full_path)):
建议用 `Path.as_posix`

2024-07-12 06:44 UTC, Fallen-Breath commented on prime_backup/config/backup_config.py
> +		'server/session.lock',
不等效。多了解下相关逻辑吧，这里有 3 个不同种类错误，不清楚就别改了

2024-07-12 06:45 UTC, chinese-wzq commented on docs/config.md
> +It is recommended to use `ignored_files_regex` to support more accurate and specific matching methods.
> `ignored_files_regex` 不是 `ignored_files` 的完全替代

那么将描述修改为“更强大的匹配”？

2024-07-12 06:45 UTC, chinese-wzq commented on prime_backup/config/backup_config.py
> +			if re.match(item, str(full_path)):
好的

2024-07-12 06:47 UTC, Fallen-Breath commented on prime_backup/config/backup_config.py
> +		'server/session.lock',
1. 正则表达式里未转义 `.`
2. 路径分隔符硬编码为 posix 下的实现，不兼容 windows
3. 假定了 MCDR 配置的服务端路径为 `server`
4. `session.lock` 的路径错误。其应当位于存档文件夹中

2024-07-12 06:53 UTC, Fallen-Breath commented
> 我现在仔细看了一下__scan_files，好像改动前后没有逻辑上没有什么差别呀，能指出来吗

改动前后没有差别，复用了仅支持文件排除的 `ignored_files` 的逻辑就是问题所在

2024-07-12 06:54 UTC, Fallen-Breath commented
我之后自己实现吧

2024-07-12 06:54 UTC, closed without merging

2024-07-12 06:57 UTC, chinese-wzq commented
> > 我现在仔细看了一下__scan_files，好像改动前后没有逻辑上没有什么差别呀，能指出来吗
> 
> 改动前后没有差别，复用了仅支持文件排除的 `ignored_files` 的逻辑就是问题所在

整个项目只有__scan_files函数一个地方用到啊，不存在复用吧

2024-07-12 07:04 UTC, chinese-wzq commented
> > 我现在仔细看了一下__scan_files，好像改动前后没有逻辑上没有什么差别呀，能指出来吗
> 
> 改动前后没有差别，复用了仅支持文件排除的 `ignored_files` 的逻辑就是问题所在

```
if not target_path.is_symlink() and target_path.is_dir():
for dir_path, dir_names, file_names in os.walk(target_path):
	for name in file_names + dir_names:
		file_path = Path(dir_path) / name
		if not self.config.backup.is_file_ignore(file_path):
			collected.append(file_path)
```
你原本的代码的逻辑就是同时用ignored_files来对所有的文件夹和文件名进行匹配啊，并不是“仅支持文件排除”